### ISSUE TITLE
Truncated transcription

### ISSUE THREAD

**Issue by mzarazov** [alumae/kaldi-gstreamer-server#76]
My workers tend to miss last word in an audio when streaming a file via the client.py

For example, when I take the following segment from eval2000

```sh
$KALDI_ROOT/egs/fisher_swbd/s5/../../..//tools/sph2pipe_v2.5/sph2pipe -f wav -p -c 2 $HUB5E/english/sw_4910.sph | sox -t wav - sw_4910-B_trimmed.wav trim '295.81' '=299.01'
```
using `gst-kaldi-nnet2-online` the hypothesis is

```
i i i'm old enough i'm over fifty
```

However, using `kaldi-gstreamer` with exactly same settings, the hypothesis is

```
i i i'm old enough i'm over
```

Is this expected? Or am I doing something wrong?

Thanks,

**Comment by alumae** [comment]
Can you paste your congif yaml file?

**Comment by mzarazov** [comment]
Yeah

```yaml
use-nnet2: True
decoder:
    nnet-mode: 3
    nnet-batch-size: 128
    model : mdl_lambda19/final.mdl
    word-syms : mdl_lambda19/words.txt
    phone-syms : mdl_lambda19/phones.txt
    fst : mdl_lambda19/HCLG.fst
    mfcc-config : mdl_lambda19/conf/mfcc.conf
    ivector-extraction-config : mdl_lambda19/conf/ivector_extractor.conf
    ivector-silence-weighting-silence-weight: 1.0
    max-active: 10000
    beam: 13.0
    lattice-beam: 6.0
    acoustic-scale: 1.0
    do-endpointing : true
    endpoint-silence-phones : "1:2:3:4:5:6:7:8:9:10:11:12:13:14:15:16:17:18:19:20"
    max-state-duration: 40
    frame-subsampling-factor: 3
    num-nbest: 10
out-dir: tmp

use-vad: False
silence-timeout: 10

post-processor: perl -npe 'BEGIN {use IO::Handle; STDOUT->autoflush(1);} s/(.*)/\1./;'
full-post-processor: ./abbrev_punct_post_processor.py

logging:
    version : 1
    disable_existing_loggers: False
    formatters:
        simpleFormater:
            format: '%(asctime)s - %(levelname)7s: %(name)10s: %(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
        console:
            class: logging.StreamHandler
            formatter: simpleFormater
            level: ERROR
    root:
        level: ERROR
        handlers: [console]
```
